CREATE TABLE IF NOT EXISTS BoardGames
(BG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
 GameTitle TEXT NOT NULL,
 PlayersMin INT NOT NULL,
 PlayersMax INT NOT NULL,
 TimeMin INT NOT NULL,
 TimeMax INT NOT NULL,
 PlayCount INT DEFAULT 0,
 UNIQUE(BG_ID, GameTitle));